repos:
  - repo: https://github.com/ambv/black
    rev: 21.10b0
    hooks:
      - id: black
        language_version: python3.6
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.20.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

# -   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
#     rev: v1.0.4
#     hooks:
#     -   id: python-bandit-vulnerability-check
#         args: [-l, --recursive, -x, tests]
#         files: .py$

# -   repo: https://github.com/asottile/reorder_python_imports
#     rev: v1.6.1
#     hooks:
#     -   id: reorder-python-imports